name: Build and Test
on:
    push:
        branches:
            - master
    pull_request:
        paths:
            - "**.ts"
            - "package*json"
            - ".github/workflows/*.yml"
jobs:
  run:
    name: Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12", "10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        run: npm run lint
      - name: Format files
        run: npm run format
      - name: Build project
        run: npm run build
      - name: Test and collect coverage info
        run: npm run collect-coverage
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.0
        with:
          commit_message: Fix format and lint issues
          branch: ${{ github.head_ref }}
